name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Adding markdown
      run: echo '###TTTTTEST! 🔒' >> $GITHUB_STEP_SUMMARY
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with: 
        version: 9.6.11
        php_version: '8.1.2'
        php_extensions: gd