name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpunit@v3
      with: 
        php-version: '8.1.2'
        extensions: gd