name: CI

on: [push]

jobs:
  build-test:
     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - uses: php-actions/composer@v6

     - name : PHP Static Analysis
      uses : php-actions/phpstan@v3
      with :
        path : lib/ /tst
        php_version: 8.1.2
        php_extensions: gd sqlite3 dom xml xdebug
	error_format : github

     - name: PHPUnit Tests
       uses: php-actions/phpunit@master
       env:
         TEST_NAME: TEST
         XDEBUG_MODE: coverage
       with:
         version: 9.6.11
         configuration: phpunit.xml
         php_version: 8.1.2
         php_extensions: gd sqlite3 dom xml xdebug
         coverage_cobertura: log/coverage-cobertura.xml

     - name : Code Coverage Summary
       uses: irongut/CodeCoverageSummary@v1.3.0
       with:
         filename: log/coverage-cobertura.xml
         badge: true
         fail_below_min: true
         format: markdown
         hide_branch_rate: false
         hide_complexity: true
         indicators: true
         output: both
         thresholds: "50 75"

     - name : "Add Mardown"
       run : cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

     - name : "PHP Code Sniffer"
       uses : php-actions/phpcs@v1
       with:
         php_version: 8.1.2
         path : lib/
         standard: phpcs.xml
         severity : 100

     - name : "PHP Mess Detector"
       uses : php-actions/phpmd@v1
       with :
         php_version: 8.1
         path : lib/
         output: text
         ruleset : phpmd_ruleset.xml
         args : --ignore-errors-on-exit --ignore-violations-on-exit

     - name : "AWS Deployment"
       uses : appleboy/scp-action@v0.1.4
       with :
         host : ${{ secrets.REMOTE_HOST }}
         username : ${{ secrets.REMOTE_USERNAME }}
         key : ${{ secrets.AWS_SSH_KEY }}
         port : 22
         source : "."
         target : /var/www/html/